"""
Django settings for trading project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

ADMINS = (
    ('Adriana', 'adi@a8.nl'),
    )

MANAGERS = ADMINS

USER_PATH           = '/Users/adriana/workspace/adriana/questionnaire_customerheartbeat_com'

ALLOWED_HOSTS = ['127.0.0.1']

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dshm@35jpdvdyi!p!zj@+hjye@b9jz9#mrg%9c!e#ibb%j+!l$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

STATICFILES_DIRS = (
    ('css',         '%s/app/css' % USER_PATH),
    ('js',          '%s/app/js' % USER_PATH),
    ('img',         '%s/app/img' % USER_PATH),
    ('lib',         '%s/app/lib' % USER_PATH),
    ('coffee',      '%s/app/coffee' % USER_PATH),
    ('partials',    '%s/app/partials' % USER_PATH)
)


# Application definition
INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'server',
]

MIDDLEWARE = [
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
]

ROOT_URLCONF = 'server.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['%s/app'%USER_PATH, '%s/app/partials'%USER_PATH],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {}


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

EMAIL_HOST          = "mailing.active8.nl"
EMAIL_HOST_PASSWORD = "k78m45aa"
EMAIL_HOST_USER     = "active8_mailer"

