// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module("questionnaireApp", ["questionnaireApp.services", "questionnaireApp.directives", "questionnaireApp.controllers", "ngRoute"]);

  app.config([
    "$routeProvider", function($routeProvider) {
      $routeProvider.when('/', {
        templateUrl: "static/partials/questionnaire/questionnaire.html",
        controller: "QuestionnaireController"
      });
      return $routeProvider.otherwise({
        redirectTo: '/'
      });
    }
  ]);

}).call(this);
