// Generated by CoffeeScript 1.7.1
(function() {
  var controllers;

  controllers = angular.module("questionnaireApp.controllers", []);

  controllers.controller('QuestionnaireController', [
    '$scope', '$location', function($scope, $location) {
      return alert('a');
    }
  ]);

}).call(this);
