// Generated by CoffeeScript 1.7.1
(function() {
  var FIREBASE_URL, services;

  services = angular.module("questionnaireApp.services", []);

  FIREBASE_URL = 'glaring-heat-5382.firebaseio.com';

}).call(this);
